name: CD workflow - Dev Environment
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  prepare-artifact:
    name: Creating Application Artifact
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - uses: nrwl/nx-set-shas@v3
      - run: npm i

      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3
      - run: npx nx affected -t build --parallel=3
